academy/urls.py
from courses.views import CourseListView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    # User management
    path(
        "users/",
        include("users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Course management
    path("courses/", include("courses.urls")),
    # Student management
    path("students/", include("students.urls")),
    # Django admin
    path("admin/", admin.site.urls),
    # Rest Api
    path("api/v1/", include("courses.api.urls", namespace="api")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/v1/dj-rest-auth/", include("dj_rest_auth.urls")),
    path(
        "api/v1/dj-rest-auth/registration/",
        include("dj_rest_auth.registration.urls"),
    ),
]

if settings.DEBUG:

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

courses/urls.py
from django.urls import path

from . import views

app_name = "courses"
urlpatterns = [
    path("", views.CourseListView.as_view(), name="course_list"),
    path(
        "mine/",
        views.ManageCourseList.as_view(),
        name="manage_course_list",
    ),
    path("create/", views.CourseCreateView.as_view(), name="course_create"),
    path("<pk>/edit/", views.CourseUpdateView.as_view(), name="course_edit"),
    path(
        "<pk>/delete/", views.CourseDeleteView.as_view(), name="course_delete"
    ),
    path(
        "<pk>/module",
        views.CourseModuleUpdateView.as_view(),
        name="course_module_update",
    ),
    path(
        "module/<int:module_id>/content/<model_name>/create/",
        views.ContentCreateUpdateView.as_view(),
        name="module_content_create",
    ),
    path(
        "module/<int:module_id>/content/<model_name>/<id>/",
        views.ContentCreateUpdateView.as_view(),
        name="module_content_update",
    ),
    path(
        "content/<int:id>/delete/",
        views.ContentDeleteView.as_view(),
        name="module_content_delete",
    ),
    path(
        "module/<int:module_id>/",
        views.ModuleContentListView.as_view(),
        name="module_content_list",
    ),
    path(
        "module/order/", views.ModuleOrderView.as_view(), name="module_order"
    ),
    path(
        "content/order/",
        views.ContentOrderView.as_view(),
        name="content_order",
    ),
    # Display all courses for a series
    path(
        "series/<slug:subject>",
        views.CourseListView.as_view(),
        name="course_list_series",
    ),
    # display a single course overview
    path(
        "<slug:slug>/", views.CourseDetailView.as_view(), name="course_detail"
    ),
]

users/urls.py
from django.urls import path

app_name = "users"
from users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'styles/courses.css' %}" />
   
    <!-- Favicons -->
    <title>{% block title %}{% endblock title %}
    </title>
</head>

<body>

    {% include "navbar.html" %}
    <div class="d-flex flex-column min-vh-100">
        <div class="container">
            <div class="mt-5">
                {% block content %}
                {% endblock content %}
            </div>
        </div>

        <footer class="text-muted mt-auto">
            <div class=" container">
                <p class="float-end mb-1">
                    <a href="#">Back to top</a>
                </p>
                <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!
                </p>
                <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                        href="/docs/5.2/getting-started/introduction/">getting started guide</a>.</p>
            </div>
        </footer>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/
jquery.min.js">
    </script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>

    <script>
        $(document).ready(function () {
            {% block domready %} 
            {% endblock domready %}
        });
    </script>
</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-dark navbar-expand-lg navbar-light bg-dark">
   <div class="container d-flex justify-content-between">
      <a class="navbar-brand" href="{% url 'home' %}">Elearning For Farmers</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
         aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
               <a class="nav-link " aria-current="page" href="#">About us</a>
            </li>
            {% if request.user.type == "STUDENT" %}
            <li class="nav-item">
               <a class="nav-link" href="{% url 'courses:course_list' %}">Courses</a>
            </li>
            {% else %}
            <li class="nav-item">
               <a class="nav-link" href="{% url 'courses:manage_course_list' %}">Courses</a>
            </li>

            {% endif %}


            <li class="nav-item">
               <a class="nav-link" href="#">Webinars</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="#">Partners</a>
            </li>
         </ul>


         {% if request.user.is_authenticated %}
         <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdown"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">
               <span class="navbar-text mx-1">{{request.user.name}}</span>
               <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="40"
                  alt="Black and White Portrait of a Man" loading="lazy" />
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
               {% if request.user.type == "STUDENT" %}
               <li>
                  <a class="dropdown-item" href="{% url 'courses:course_list' %}">Dashboard</a>
               </li>
               {% else %}
               <li>
                  <a class="dropdown-item" href="{% url 'courses:manage_course_list' %}">Dashboard</a>
               </li>

               {% endif %}

               <li>
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">My profile</a>
               </li>
               <li>
                  <a class="dropdown-item" href="#">Settings</a>
               </li>
               <li>
                  <hr class="dropdown-divider">
               </li>
               <li>
                  <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
               </li>
            </ul>
         </div>
         {% else %}

         <span class="navbar-text">
            You are not logged in.
         </span>
         (<a href="{% url 'account_login' %}">Log in</a>) <a href="{% url 'account_signup' %}">Register</a>
         {% endif %}

      </div>
   </div>
</nav>